[paths]
template_path = "templates/"
granite_path = "pages-test/"
html_path = "docs-test/"
plugin_path = "plugins/"
music_path = "/home/user/Music/"

[values]
latest_length = 15
last_run = 1652823533
