# Site settings
title_left    : "Mineral Existence"
title_right   : ""
description   : "A blog of programming, rambling, and miscellaneous thoughts"
intro         : "Hello there! I'm Ben, and this is my blog where I ramble about projects I'm working on, ideas I have, and other miscellaneous bits and bobs"
keywords      : "blog, programming, gamedev, procgen"
url           : https://flber.github.io # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "https://github.com/flber.png" # image uri like logo/cover image for site seo

google_analytics  : UA-173547026-1
twitter_username  : "flbr14"
comments_enabled  : true # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "flber-github-io"
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Ben Hammond"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
